<?php
/**
 * SessionState
 *
 * PHP version 5
 *
 * @category Class
 * @package  Equisoft\SDK\AccountService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * User account and session management
 *
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Equisoft\SDK\AccountService\Model;
use \Equisoft\SDK\AccountService\ObjectSerializer;

/**
 * SessionState Class Doc Comment
 *
 * @category Class
 * @description States: * &#x60;NEW&#x60; - Session creation is not finished.  It can&#39;t be used by consumer. * &#x60;ENABLED&#x60; - Session is active and ready. * &#x60;SUSPENDED&#x60; - Session idle for too long.  User has to reenter credentials to activate it (Not implemented yet). * &#x60;EXPIRED&#x60; - Session is expired. * &#x60;DELETED&#x60; - Session exists but is soft-deleted (Not implemented yet).
 * @package  Equisoft\SDK\AccountService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SessionState
{
    /**
     * Possible values of this enum
     */
    const _NEW = 'NEW';
    const ENABLED = 'ENABLED';
    const SUSPENDED = 'SUSPENDED';
    const EXPIRED = 'EXPIRED';
    const DELETED = 'DELETED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::ENABLED,
            self::SUSPENDED,
            self::EXPIRED,
            self::DELETED,
        ];
    }
}


