<?php
/**
 * ImpersonatePayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Equisoft\SDK\AccountService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * User account and session management
 *
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\AccountService;

use PHPUnit\Framework\TestCase;

/**
 * ImpersonatePayloadTest Class Doc Comment
 *
 * @category    Class
 * @description Parameters needed to impersonanted a user for a user session
 * @package     Equisoft\SDK\AccountService
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ImpersonatePayloadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ImpersonatePayload"
     */
    public function testImpersonatePayload()
    {
    }

    /**
     * Test attribute "userUuid"
     */
    public function testPropertyUserUuid()
    {
    }
}
