<?php
/**
 * SessionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Equisoft\SDK\AccountService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * User account and session management
 *
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\AccountService;

use PHPUnit\Framework\TestCase;

/**
 * SessionTest Class Doc Comment
 *
 * @category    Class
 * @description Session
 * @package     Equisoft\SDK\AccountService
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SessionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Session"
     */
    public function testSession()
    {
    }

    /**
     * Test attribute "sessionId"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "suspend"
     */
    public function testPropertySuspend()
    {
    }

    /**
     * Test attribute "expire"
     */
    public function testPropertyExpire()
    {
    }

    /**
     * Test attribute "cookieDomain"
     */
    public function testPropertyCookieDomain()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "actor"
     */
    public function testPropertyActor()
    {
    }

    /**
     * Test attribute "sso"
     */
    public function testPropertySso()
    {
    }

    /**
     * Test attribute "enabledForEquisoftConnect"
     */
    public function testPropertyEnabledForEquisoftConnect()
    {
    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {
    }
}
