<?php
/**
 * UserDatabaseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Equisoft\SDK\AccountService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * User account and session management
 *
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Equisoft\SDK\AccountService;

use PHPUnit\Framework\TestCase;

/**
 * UserDatabaseTest Class Doc Comment
 *
 * @category    Class
 * @description UserDatabase
 * @package     Equisoft\SDK\AccountService
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserDatabaseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserDatabase"
     */
    public function testUserDatabase()
    {
    }

    /**
     * Test attribute "databaseId"
     */
    public function testPropertyDatabaseId()
    {
    }

    /**
     * Test attribute "databaseName"
     */
    public function testPropertyDatabaseName()
    {
    }

    /**
     * Test attribute "databaseState"
     */
    public function testPropertyDatabaseState()
    {
    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "maxConcurrentAccess"
     */
    public function testPropertyMaxConcurrentAccess()
    {
    }
}
