<?php
/**
 * ServiceAccountApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Equisoft\SDK\AccountService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * User account and session management
 *
 * Provides HTTP endpoints to manage User Accounts and User Sessions.
 *
 * The version of the OpenAPI document: 0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Equisoft\SDK\AccountService\Test\Api;

use \Equisoft\SDK\AccountService\Configuration;
use \Equisoft\SDK\AccountService\ApiException;
use \Equisoft\SDK\AccountService\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServiceAccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  Equisoft\SDK\AccountService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceAccountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createServiceAccount
     *
     * Creates a new service account.
     *
     */
    public function testCreateServiceAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getServiceAccount
     *
     * Get detailed information about a user account..
     *
     */
    public function testGetServiceAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchServiceAccount
     *
     * Searches service accounts that match ALL params. If none are provided, returns all service accounts.
     *
     */
    public function testSearchServiceAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateServiceAccount
     *
     * Updates a service account by uuid.
     *
     */
    public function testUpdateServiceAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
